### ISSUE TITLE
Failed launch container during docker-compose file

### ISSUE THREAD

**Issue by federicobaiamonte** [Arana-Jayavihan/Ethereum-Private-Network-On-Docker#1]
I tried to start your repository, I started both .sh files with root permissions but when starting the docker-compose.yml these errors appear on the terminal:

federico34@ubuntu:~/Documenti/git/Ethereum-Private-Network-On-Docker$ docker-compose up 
Recreating ethereum-private-network-on-docker_geth-bootnode_1 ... error

ERROR: for ethereum-private-network-on-docker_geth-bootnode_1  Cannot start service geth-bootnode: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "bootnode": executable file not found in $PATH: unknown

ERROR: for geth-bootnode  Cannot start service geth-bootnode: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "bootnode": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by Arana-Jayavihan** [comment]
Hi,

I believe that you are on a ubuntu distro. Otherwise the dependencies will
not be properly installed with the script.

I'll try to recreate the error and get back to you.

Thanks for raising the issue.

**Comment by federicobaiamonte** [comment]
I tested the entire repository on a clean VM with Ubuntu 22.04 LTS and it works perfectly. I had tried it first on the other physical partition with Ubuntu 22.04 with docker already installed. Thank you for answering.

**Comment by Arana-Jayavihan** [comment]
Metbe you had a conflicting version of geth.
